language: php

php:
  - 7.4
  - 8.0

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.composer/vendor

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
